name: '    Walk to Threnody '
favicon: null
layout_spectrum: 0.243
typography_spectrum: 0.231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#585276'
    - '#1b0d31'
    - '#94abff'
    - '#ff7847'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
