name: '    Walk to Threnody '
favicon: null
layout_spectrum: 0.993
typography_spectrum: 0.231
title: The.permanent.record
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262e39'
    - '#2878d2'
    - '#6ebbeb'
    - '#d83636'
    - '#b88686'
  brandStrength: 0
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
