name: '    Walk to Threnody '
favicon: null
layout_spectrum: 0.99718
typography_spectrum: 0.5047
title: The.permanent.record
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#668199'
    - '#c2c8cd'
    - '#382a28'
    - '#5d6271'
    - '#69afb5'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
