name: '    Walk to Threnody '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b6b8b3'
    - '#5c6271'
    - '#2c2929'
    - '#c5704d'
  brandStrength: 0.9153668778017163
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
