name: '    Walk to Threnody '
favicon: null
layout_spectrum: 0.99906
typography_spectrum: 0.98778
title: The.permanent.record
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9d9c98'
    - '#f09e04'
    - '#564e46'
    - '#db3813'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
